### ISSUE TITLE
Code of the model and evaluation

### ISSUE THREAD

**Issue by yclzju** [yaolu/Multi-XScience#1]
Hi, I am really interesting in your work, could you plz also release your code about models for the experiments( I want to know if you change original model for this new setting, how do you organize your data to the model), and your code about evaluation.

**Comment by yaolu** [comment]
Hi,

Thanks for reaching out. Please take a look at the appendix of our paper https://yaolu.github.io/upload/multixscience/Multi_XScience_Appendix.pdf

Some of these models are multi-document models. You can use the original implementation (source code link in appendix) to preprocess Multi-XScience. No need to change any line of code. (fusion model described in our paper)

For these models designed for single-document summarization, we concatenate all multi-document inputs into a single document, then feed into these models. (concat mode described in our paper)

Yao Lu

**Comment by yclzju** [comment]
Thanks for your reply. Do you only use the information of the text, no other aditional input, such as "cite_2", right? And during training, you don't replace the cite_2 in reference abstract, but replace to "cite" while evaluation?

**Comment by yaolu** [comment]
Only text information is used in this paper for all models.

If I understand correctly, your "additional input" means use these explicit cite_N symbols as additional supervision for summarization? If yes, you can take a look at page 6 of the slides https://yaolu.github.io/upload/multixscience/Multi-XScience-EMNLP.pdf .

During training and inference, all cite_N symbols are replaced with the same cite symbol.

**Comment by yaolu** [comment]
Resolved. Feel free to reopen.
