### ISSUE TITLE
Human evaluation

### ISSUE THREAD

**Issue by JessicaLopezEspejel** [yaolu/Multi-XScience#2]
Hello!
I would like to know if I can have access to the 25 samples you  randomly and the human judges scores.

**Comment by yaolu** [comment]
Hi,

Do you mean the dataset quality analysis in Section 2.4 or model generation quality analysis in Section 3.3?

Yao

**Comment by JessicaLopezEspejel** [comment]
> Hi,
> 
> Do you mean the dataset quality analysis in Section 2.4 or model generation quality analysis in Section 3.3?
> 
> Yao

I mean quality analysis in Section 2.4

**Comment by yaolu** [comment]
Here is the file.

[dataset_quality.zip](https://github.com/yaolu/Multi-XScience/files/5527806/dataset_quality.zip)

**Comment by JessicaLopezEspejel** [comment]
> Here is the file.
> 
> [dataset_quality.zip](https://github.com/yaolu/Multi-XScience/files/5527806/dataset_quality.zip)

Thank you @yaolu
