### ISSUE TITLE
implementing n-gram repeat blocking

### ISSUE THREAD

**Issue by Tinarights** [yaolu/Multi-XScience#6]
How did you implement tri-gram or ngram blocking in pointer-generator project?
Could you please help

**Comment by yaolu** [comment]
You can take this as reference
https://github.com/nlpyang/hiersumm/blob/476e6bf9c716326d6e4c27d5b6878d0816893659/src/abstractive/beam.py#L153

**Comment by Tinarights** [comment]
Is it possible to share the piece of code? It will be highly appreciated.

**Comment by yaolu** [comment]
If you use https://github.com/abisee/pointer-generator for summarization, you can replace beam_search.py and decode.py with the following version. It will block trigram. 
[code.zip](https://github.com/yaolu/Multi-XScience/files/7822157/code.zip)

**Comment by Tinarights** [comment]
Thanks a lot. Really appreciate that.
I still couldn't reproduce the exact results on PG.
In your paper, you mentioned the **min_dec_steps=110**, but what is the **max_dec_steps**?
How many training steps have you done?

Thanks
