### ISSUE TITLE
doubt: a much lower rouge score of pointer-generator

### ISSUE THREAD

**Issue by muguruzawang** [yaolu/Multi-XScience#7]
The rouge(1/2/L) score of pointer-generator reported in the paper is: 34.11/6.76/30.63 ,
however, I run the pointer-generator model (guided by https://opennmt.net/OpenNMT-py/examples/Summarization.html) but find the rouge is: 30/5.11/26.42, when training for 200,000 steps. 
So could you please provide me your pointer-generator model result, or your training setting?

**Comment by muguruzawang** [comment]
@yaolu

**Comment by yaolu** [comment]
Here is the pointer-generator output.

[pointer-generator.zip](https://github.com/yaolu/Multi-XScience/files/7657485/pointer-generator.zip)

**Comment by Tinarights** [comment]
@yaolu Thank you for your help.
Do you merge the decoded files into one .txt file before calculating rouge?

I trained 120K steps in the PG, and got Rouges [0.3009, 0.0504, 0.1628]
Testing multi files produce very low Rouge-L scores.


but when I merge the decoded files [0000decoded.txt, 0001decoded.txt......] into a single text file, and do the same for the ref files, the score of Rouge-L rises into 25, got Rouges=[0.3009, 0.0504, 0.2575]

Do you what is the reason? 

And could you please let me know whats the value you used for max_dec_steps?

Many thanks,
